tushare: bugfix for trading dates changing from ascending order to descending order
As the title says, the tushare get_trading_dates API has been changed. We encountered this
stack as follows:

Traceback (most recent call last):
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 78, in value
    return self.series[-1]
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 275, in series
    self._ensure_series_update()
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 251, in _ensure_series_update
    bars = get_bars(freq)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 20, in get_bars
    bars = data_backend.get_price(order_book_id, start=start_date, end=current_date, freq=freq)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/data/tushare_backend.py", line 97, in get_price
    last_tradeday = self.get_trading_dates(start, end)[-2]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/project/stock/choose_stock.py", line 283, in <module>
    price = C.value
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 80, in value
    raise FormulaException("DATA UNAVAILABLE")
funcat.utils.FormulaException: DATA UNAVAILABLE

Signed-off-by: Guanjun <guanjun@linux.alibaba.com>