bugfix: fix numpy deprecated alias for builtin int
The issue's stack is as follows:
```
Traceback (most recent call last):
  File "/root/project/funcat/for_stocks/choose_stock.py", line 260, in <module>
    select(
  File "/root/.conda/envs/py310/lib/python3.10/site-packages/funcat/helper.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/root/.conda/envs/py310/lib/python3.10/site-packages/funcat/helper.py", line 55, in select
    choose(order_book_id, func, callback)
  File "/root/.conda/envs/py310/lib/python3.10/site-packages/funcat/helper.py", line 27, in choose
    if func():
  File "/root/project/funcat/for_stocks/choose_stock.py", line 261, in <lambda>
    lambda: select_over_average(31) and select_long_average_up(5) and select_down_from_max(31, 1.12) and HHV(H, 21) / C > 1.12,
  File "/root/project/funcat/for_stocks/choose_stock.py", line 81, in select_over_average
    ret = (COUNT((C[i] > MA(C[i], 5)) & (C[i] > MA(C[i], 13)) & (C[i] > MA(C[i], 21)) & (C[i] > MA(C[i], 34)) & (C[i] > MA(C[i], 55)), n) == 1)
  File "/root/.conda/envs/py310/lib/python3.10/site-packages/funcat/utils.py", line 100, in wrapper
    return func(*args, **kwargs)
  File "/root/.conda/envs/py310/lib/python3.10/site-packages/funcat/func.py", line 190, in count
    result = np.full(size, 0, dtype=np.int)
  File "/root/.conda/envs/py310/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

This patch fix this issue

Signed-off-by: Guanjun <guanjun@linux.alibaba.com>