tencent: fix connection timeout issues
Tencent runtime API may be not reliable. We encounter several exceptions
these days and the trace are as follows:

Traceback (most recent call last):
  File "/root/choose_stock.py", line 245, in <module>
    select(
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/helper.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/helper.py", line 54, in select
    choose(order_book_id, func, callback)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/helper.py", line 27, in choose
    if func():
  File "/root/choose_stock.py", line 246, in <lambda>
    lambda: select_over_average(31) and select_long_average_up(5) and select_down_from_max(31, 1.12) and HHV(H, 21) / C > 1.12,
  File "/root/choose_stock.py", line 71, in select_over_average
    ma5 = MA(C[i], 5)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 271, in __getitem__
    return self.__class__(series=self.series[:len(self.series) - index], **self.extra_create_kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 275, in series
    self._ensure_series_update()
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 251, in _ensure_series_update
    bars = get_bars(freq)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/time_series.py", line 20, in get_bars
    bars = data_backend.get_price(order_book_id, start=start_date, end=current_date, freq=freq)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/data/tushare_backend.py", line 151, in get_price
    rt = get_runtime_data(order_book_id)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/funcat-1.1.0-py3.9.egg/funcat/data/rt_data_from_tencent.py", line 14, in get_runtime_data
    text = requests.get(url + code_suffix)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='qt.gtimg.cn', port=80): Max retries exceeded with url: /q=sz000960 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c9df0b4c0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Signed-off-by: Guanjun <guanjun@linux.alibaba.com>