func: bugfix for missing 1 required positional argument
When function type switching from instance to class, The SMASeries
self defined function should also be changed.

Otherwise, it will encounter this issue when invoke SMA(C, arg1, arg2).

  Traceback (most recent call last):
    File "/root/miniconda3/envs/py36/lib/python3.6/site-packages/funcat-1.1.0-py3.6.egg/funcat/func.py", line 75, in __init__
      series = self.__class__.func(series, arg1, arg2)
  TypeError: func() missing 1 required positional argument: '_'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "test.py", line 65, in <module>
      if C<REF(C,1) and ZJFZ()>=0.1 and CCI()[-1]<=-110:
    File "test.py", line 27, in ZJFZ
      VAR3=SMA(ABS(L-VAR2),3,1)/SMA(MAX(L-VAR2,0),3,1)*100
    File "/root/miniconda3/envs/py36/lib/python3.6/site-packages/funcat-1.1.0-py3.6.egg/funcat/func.py", line 77, in __init__
      raise FormulaException(e)
  funcat.utils.FormulaException: func() missing 1 required positional argument: '_'

Fixes: 85b729a8d933 (talib: support higher TA-Lib versions.)
Signed-off-by: Guanjun <guanjun@linux.alibaba.com>